create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('owner','editor','viewer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content_records (
  kind text not null check (kind in ('jobs','exams','results','admit_cards','blog')),
  id text not null,
  payload jsonb not null default '{}'::jsonb,
  published boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (kind,id)
);
create unique index if not exists admin_one_owner_uidx on public.admin_users ((role)) where role='owner';

create index if not exists content_records_kind_published_idx on public.content_records(kind,published);
create or replace function public.validate_content_payload() returns trigger language plpgsql security definer set search_path=public as $$
begin
  if jsonb_typeof(new.payload) <> 'object' then raise exception 'Content payload must be a JSON object'; end if;
  if new.kind='jobs' then
    if coalesce(length(trim(new.payload->>'title')),0)=0 or coalesce(length(trim(new.payload->>'org')),0)=0 then raise exception 'Job title and organization are required'; end if;
    if new.payload ? 'category' and (new.payload->>'category') not in ('Government','Private','Bank','Railway','Teaching','Defence','Police','Apprentice') then raise exception 'Invalid job category'; end if;
    if new.payload ? 'jobType' and (new.payload->>'jobType') not in ('Permanent','Contractual','Apprentice','Full Time') then raise exception 'Invalid job type'; end if;
  elsif new.kind='exams' then
    if coalesce(length(trim(new.payload->>'examName')),0)=0 or coalesce(length(trim(new.payload->>'org')),0)=0 then raise exception 'Exam name and organization are required'; end if;
  elsif new.kind='results' then
    if coalesce(length(trim(new.payload->>'resultTitle')),0)=0 or coalesce(length(trim(new.payload->>'org')),0)=0 then raise exception 'Result title and organization are required'; end if;
  elsif new.kind='admit_cards' then
    if coalesce(length(trim(new.payload->>'examName')),0)=0 or coalesce(length(trim(new.payload->>'org')),0)=0 then raise exception 'Exam name and organization are required'; end if;
  elsif new.kind='blog' then
    if coalesce(length(trim(new.payload->>'title')),0)=0 or coalesce(length(trim(new.payload->>'content')),0)=0 then raise exception 'Blog title and content are required'; end if;
  end if;
  new.payload=jsonb_set(new.payload,'{published}',to_jsonb(new.published),true);
  return new;
end; $$;
drop trigger if exists content_payload_validate on public.content_records;
create trigger content_payload_validate before insert or update on public.content_records for each row execute function public.validate_content_payload();
revoke all on function public.validate_content_payload() from public;


create table if not exists public.site_config (
  key text primary key check (key in ('settings','features')),
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view','job_view','apply_click','whatsapp_click','search')),
  label text check (label is null or length(label)<=200),
  visitor_key text,
  created_at timestamptz not null default now()
);
create index if not exists analytics_events_created_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_type_created_idx on public.analytics_events(event_type,created_at desc);
create index if not exists analytics_events_search_idx on public.analytics_events(event_type,label) where event_type='search';

create table if not exists public.ad_slots (
  id text primary key,
  title text not null,
  location_name text not null,
  html_content text not null default '',
  enabled boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  endpoint text primary key,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.content_records enable row level security;
alter table public.site_config enable row level security;
alter table public.analytics_events enable row level security;
alter table public.ad_slots enable row level security;
alter table public.push_subscriptions enable row level security;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.admin_users a where a.user_id=auth.uid());
$$;
create or replace function public.is_editor() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.role in ('owner','editor'));
$$;
create or replace function public.is_owner() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.role='owner');
$$;

revoke all on function public.is_admin() from public; grant execute on function public.is_admin() to anon,authenticated;
revoke all on function public.is_editor() from public; grant execute on function public.is_editor() to authenticated;
revoke all on function public.is_owner() from public; grant execute on function public.is_owner() to authenticated;

 drop policy if exists admin_self_read on public.admin_users;
create policy admin_self_read on public.admin_users for select using (user_id=auth.uid());
drop policy if exists admin_owner_write on public.admin_users;
create policy admin_owner_write on public.admin_users for all using (public.is_owner()) with check (public.is_owner());

drop policy if exists content_public_read on public.content_records;
create policy content_public_read on public.content_records for select using (published=true or public.is_admin());
drop policy if exists content_admin_write on public.content_records;
create policy content_admin_write on public.content_records for all using (public.is_editor()) with check (public.is_editor());

drop policy if exists config_public_read on public.site_config;
create policy config_public_read on public.site_config for select using (true);
drop policy if exists config_owner_write on public.site_config;
create policy config_owner_write on public.site_config for all using (public.is_owner()) with check (public.is_owner());

drop policy if exists ads_public_read on public.ad_slots;
create policy ads_public_read on public.ad_slots for select using (enabled=true or public.is_admin());
drop policy if exists ads_admin_write on public.ad_slots;
create policy ads_admin_write on public.ad_slots for all using (public.is_editor()) with check (public.is_editor());

drop policy if exists analytics_public_insert on public.analytics_events;
drop policy if exists analytics_admin_read on public.analytics_events;
create policy analytics_admin_read on public.analytics_events for select using (public.is_admin());

-- Public analytics writes cannot read, update or delete arbitrary events.
revoke select,update,delete on public.analytics_events from anon;
create or replace function public.record_analytics_event(p_event_type text,p_label text,p_visitor_key text) returns void language plpgsql security definer set search_path=public as $$
begin
  if p_event_type not in ('page_view','job_view','apply_click','whatsapp_click','search') then raise exception 'Invalid analytics event'; end if;
  if p_label is not null and length(p_label)>200 then raise exception 'Analytics label too long'; end if;
  if p_visitor_key is null or length(trim(p_visitor_key))<16 or length(p_visitor_key)>128 then raise exception 'Invalid analytics visitor key'; end if;
  if exists(select 1 from public.analytics_events where visitor_key=p_visitor_key and event_type=p_event_type and created_at>now()-interval '2 seconds') then return; end if;
  if (select count(*) from public.analytics_events where visitor_key=p_visitor_key and created_at>now()-interval '1 minute') >= 30 then return; end if;
  insert into public.analytics_events(event_type,label,visitor_key) values(p_event_type,nullif(trim(p_label),''),p_visitor_key);
end; $$;
revoke all on function public.record_analytics_event(text,text,text) from public; grant execute on function public.record_analytics_event(text,text,text) to anon,authenticated;


create or replace function public.analytics_summary()
returns table(event_type text,event_count bigint)
language sql stable security definer set search_path=public as $$
 select event_type,count(*) from public.analytics_events group by event_type;
$$;
create or replace function public.analytics_searches()
returns table(term text,event_count bigint)
language sql stable security definer set search_path=public as $$
 select label,count(*) from public.analytics_events where event_type='search' and label is not null group by label order by count(*) desc limit 15;
$$;
revoke all on function public.analytics_summary() from public; grant execute on function public.analytics_summary() to authenticated;
revoke all on function public.analytics_searches() from public; grant execute on function public.analytics_searches() to authenticated;

create or replace function public.upsert_admin_by_email(p_email text,p_role text) returns void language plpgsql security definer set search_path=public,auth as $$
declare uid uuid; begin
 if not public.is_owner() then raise exception 'Owner permission required'; end if;
 if p_role not in ('owner','editor','viewer') then raise exception 'Invalid role'; end if;
 select id into uid from auth.users where lower(email)=lower(trim(p_email)) limit 1;
 if uid is null then raise exception 'No Supabase user exists for this email'; end if;
 if p_role='owner' and exists(select 1 from public.admin_users where role='owner' and user_id<>uid) then raise exception 'Only one owner is allowed'; end if;
 insert into public.admin_users(user_id,role) values(uid,p_role) on conflict(user_id) do update set role=excluded.role,updated_at=now();
end; $$;
revoke all on function public.upsert_admin_by_email(text,text) from public; grant execute on function public.upsert_admin_by_email(text,text) to authenticated;

create or replace function public.remove_admin_by_email(p_email text) returns void language plpgsql security definer set search_path=public,auth as $$
declare uid uuid; begin
 if not public.is_owner() then raise exception 'Owner permission required'; end if;
 select id into uid from auth.users where lower(email)=lower(trim(p_email)) limit 1;
 if uid is not null then if uid=auth.uid() then raise exception 'You cannot remove your own owner account'; end if; delete from public.admin_users where user_id=uid; end if;
end; $$;
revoke all on function public.remove_admin_by_email(text) from public; grant execute on function public.remove_admin_by_email(text) to authenticated;
create or replace function public.list_admin_users() returns table(user_id uuid,email text,role text,created_at timestamptz,updated_at timestamptz) language sql security definer set search_path=public,auth as $$
 select a.user_id,u.email,a.role,a.created_at,a.updated_at from public.admin_users a join auth.users u on u.id=a.user_id where public.is_owner() order by a.created_at;
$$;
revoke all on function public.list_admin_users() from public; grant execute on function public.list_admin_users() to authenticated;


-- Atomic single-record operations; these avoid stale browser snapshot overwrites.
create or replace function public.delete_content_record(p_kind text,p_id text) returns void language plpgsql security definer set search_path=public as $$
begin if not public.is_editor() then raise exception 'Editor permission required'; end if; delete from public.content_records where kind=p_kind and id=p_id; end; $$;
create or replace function public.set_content_published(p_kind text,p_id text,p_published boolean) returns void language plpgsql security definer set search_path=public as $$
begin if not public.is_editor() then raise exception 'Editor permission required'; end if; update public.content_records set published=p_published, payload=jsonb_set(payload,'{published}',to_jsonb(p_published),true), updated_at=now() where kind=p_kind and id=p_id; end; $$;
revoke all on function public.delete_content_record(text,text) from public; grant execute on function public.delete_content_record(text,text) to authenticated;
revoke all on function public.set_content_published(text,text,boolean) from public; grant execute on function public.set_content_published(text,text,boolean) to authenticated;

insert into public.site_config(key,value) values
('settings','{"whatsappNumber":"","whatsappChannelUrl":"","telegramChannelUrl":"","defaultSupportMsg":"Hello JOB KHOJ Support, I have an inquiry regarding recruitment notifications.","whatsappApplyMsgTemplate":"Hello JOB KHOJ, I want information regarding Job: {{JOB_TITLE}}, Job ID: {{JOB_ID}}","enableWhatsappApplyGlobal":true,"enableHeaderWhatsappBtn":true,"siteTagline":"Find Your Next Opportunity","supportEmail":"","footerAboutText":"JOB KHOJ - Dedicated Indian Job Alert & Recruitment Information Portal"}'::jsonb),
('features','{"announcementEnabled":false,"announcementText":"Latest Government Job Updates — Check new vacancies daily.","announcementUrl":"/jobs","popupEnabled":false,"popupTitle":"Get Job Alerts","popupMessage":"Join our Telegram and WhatsApp channels for the latest updates.","popupUrl":"/","popupDelayMs":5000,"seoSiteTitle":"Job Khoj - Latest Government Jobs, Results & Admit Cards","seoSiteDescription":"Latest government jobs, recruitment notifications, results, admit cards, answer keys and exam updates.","seoKeywords":"government jobs, sarkari job, recruitment, admit card, results, job alerts","seoCanonicalUrl":"","pushNotificationsEnabled":false,"redirectRules":[]}'::jsonb)
on conflict(key) do nothing;

insert into public.ad_slots(id,title,location_name) values
('slot-1','Header Banner — Top of public pages','Header Banner'),('slot-2','Homepage Banner — Under hero section','Homepage Top'),('slot-3','Jobs Directory Banner — Top of jobs listing','Job Listing Top'),('slot-4','Job Detail Top Banner — Top of job recruitment notice','Job Detail Top'),('slot-6','Sidebar Placement Banner','Sidebar') on conflict(id) do nothing;

-- Normalize legacy duplicate owners/slugs before creating unique indexes.
with ranked as (select user_id,row_number() over(order by created_at,user_id) rn from public.admin_users where role='owner') delete from public.admin_users a using ranked r where a.user_id=r.user_id and r.rn>1;
with ranked as (select ctid,row_number() over(partition by payload->>'slug' order by updated_at,id) rn from public.content_records where kind='jobs' and coalesce(payload->>'slug','')<>'') update public.content_records c set payload=jsonb_set(c.payload,'{slug}',to_jsonb((c.payload->>'slug')||'-'||left(md5(c.id),8)),true) from ranked r where c.ctid=r.ctid and r.rn>1;
with ranked as (select ctid,row_number() over(partition by payload->>'slug' order by updated_at,id) rn from public.content_records where kind='blog' and coalesce(payload->>'slug','')<>'') update public.content_records c set payload=jsonb_set(c.payload,'{slug}',to_jsonb((c.payload->>'slug')||'-'||left(md5(c.id),8)),true) from ranked r where c.ctid=r.ctid and r.rn>1;

-- Stable slug uniqueness. Payload IDs are retained as text by the application; existing installations should migrate IDs before enabling this index.
create unique index if not exists content_jobs_slug_uidx on public.content_records ((payload->>'slug')) where kind='jobs' and coalesce(payload->>'slug','')<>'';
create unique index if not exists content_blog_slug_uidx on public.content_records ((payload->>'slug')) where kind='blog' and coalesce(payload->>'slug','')<>'';

create or replace function public.restore_content_backup(p_backup jsonb) returns void language plpgsql security definer set search_path=public as $$
declare i jsonb; begin
 if not public.is_owner() then raise exception 'Owner permission required'; end if;
 if coalesce(p_backup->>'version','') not in ('3','4') then raise exception 'Unsupported backup version'; end if;
 if jsonb_typeof(p_backup->'jobs')<>'array' or jsonb_typeof(p_backup->'exams')<>'array' or jsonb_typeof(p_backup->'results')<>'array' or jsonb_typeof(p_backup->'admitCards')<>'array' or jsonb_typeof(p_backup->'blog')<>'array' then raise exception 'Invalid backup collections'; end if;
 for i in select * from jsonb_array_elements(p_backup->'jobs') loop if coalesce(i->>'id','')='' then raise exception 'Invalid job id'; end if; end loop;
 for i in select * from jsonb_array_elements(p_backup->'exams') loop if coalesce(i->>'id','')='' then raise exception 'Invalid exam id'; end if; end loop;
 for i in select * from jsonb_array_elements(p_backup->'results') loop if coalesce(i->>'id','')='' then raise exception 'Invalid result id'; end if; end loop;
 for i in select * from jsonb_array_elements(p_backup->'admitCards') loop if coalesce(i->>'id','')='' then raise exception 'Invalid admit card id'; end if; end loop;
 for i in select * from jsonb_array_elements(p_backup->'blog') loop if coalesce(i->>'id','')='' then raise exception 'Invalid blog id'; end if; end loop;
 if p_backup ? 'adSlots' and jsonb_typeof(p_backup->'adSlots')<>'array' then raise exception 'Invalid adSlots'; end if;
 if exists(select 1 from (select i->>'id' id, count(*) c from jsonb_array_elements(p_backup->'jobs') i group by 1 having count(*)>1) q) then raise exception 'Duplicate job IDs in backup'; end if;
 if exists(select 1 from (select i->>'slug' slug, count(*) c from jsonb_array_elements(p_backup->'jobs') i where coalesce(i->>'slug','')<>'' group by 1 having count(*)>1) q) then raise exception 'Duplicate job slugs in backup'; end if;
 if exists(select 1 from (select i->>'slug' slug, count(*) c from jsonb_array_elements(p_backup->'blog') i where coalesce(i->>'slug','')<>'' group by 1 having count(*)>1) q) then raise exception 'Duplicate blog slugs in backup'; end if;
 if p_backup ? 'settings' and jsonb_typeof(p_backup->'settings')<>'object' then raise exception 'Invalid settings object'; end if;
 if p_backup ? 'features' and jsonb_typeof(p_backup->'features')<>'object' then raise exception 'Invalid features object'; end if;
 if p_backup ? 'adSlots' then
   for i in select * from jsonb_array_elements(p_backup->'adSlots') loop
     if coalesce(i->>'id','')='' or coalesce(i->>'title','')='' or coalesce(i->>'locationName','')='' then raise exception 'Invalid ad slot'; end if;
   end loop;
 end if;
 delete from public.content_records;
 for i in select * from jsonb_array_elements(p_backup->'jobs') loop insert into public.content_records(kind,id,payload,published) values('jobs',i->>'id',i,coalesce((i->>'published')::boolean,false)); end loop;
 for i in select * from jsonb_array_elements(p_backup->'exams') loop insert into public.content_records(kind,id,payload,published) values('exams',i->>'id',i,coalesce((i->>'published')::boolean,false)); end loop;
 for i in select * from jsonb_array_elements(p_backup->'results') loop insert into public.content_records(kind,id,payload,published) values('results',i->>'id',i,coalesce((i->>'published')::boolean,false)); end loop;
 for i in select * from jsonb_array_elements(p_backup->'admitCards') loop insert into public.content_records(kind,id,payload,published) values('admit_cards',i->>'id',i,coalesce((i->>'published')::boolean,false)); end loop;
 for i in select * from jsonb_array_elements(p_backup->'blog') loop insert into public.content_records(kind,id,payload,published) values('blog',i->>'id',i,coalesce((i->>'published')::boolean,false)); end loop;
 if p_backup ? 'settings' then insert into public.site_config(key,value,updated_at) values('settings',p_backup->'settings',now()) on conflict(key) do update set value=excluded.value,updated_at=now(); end if;
 if p_backup ? 'features' then insert into public.site_config(key,value,updated_at) values('features',(p_backup->'features') - 'adminUsers',now()) on conflict(key) do update set value=excluded.value,updated_at=now(); end if;
 if p_backup ? 'adSlots' then
   delete from public.ad_slots;
   for i in select * from jsonb_array_elements(p_backup->'adSlots') loop insert into public.ad_slots(id,title,location_name,html_content,enabled,updated_at) values(i->>'id',i->>'title',i->>'locationName',coalesce(i->>'htmlContent',''),coalesce((i->>'enabled')::boolean,false),now()); end loop;
 end if;
end; $$;
revoke all on function public.restore_content_backup(jsonb) from public; grant execute on function public.restore_content_backup(jsonb) to authenticated;

create or replace function public.expire_due_jobs() returns integer language plpgsql security definer set search_path=public as $$
declare changed integer:=0; r record; d date; new_status text;
begin
 if not public.is_admin() then raise exception 'Admin permission required'; end if;
 for r in select id,payload,published from public.content_records where kind='jobs' loop
   begin d:=coalesce(nullif(r.payload->>'lastDateISO','')::date, nullif(r.payload->>'lastDate','')::date); exception when others then d:=null; end;
   if d is null then continue; end if;
   if d < current_date and r.published then update public.content_records set published=false,payload=jsonb_set(jsonb_set(payload,'{published}','false'::jsonb,true),'{status}','"Expired"'::jsonb,true),updated_at=now() where kind='jobs' and id=r.id; changed:=changed+1;
   elsif r.published and d <= current_date+7 and coalesce(r.payload->>'status','')<>'Closing Soon' then update public.content_records set payload=jsonb_set(payload,'{status}','"Closing Soon"'::jsonb,true),updated_at=now() where kind='jobs' and id=r.id; changed:=changed+1;
   elsif r.published and d > current_date+7 and coalesce(r.payload->>'status','')='Closing Soon' then update public.content_records set payload=jsonb_set(payload,'{status}','"Active"'::jsonb,true),updated_at=now() where kind='jobs' and id=r.id; changed:=changed+1;
   end if;
 end loop; return changed; end; $$;
revoke all on function public.expire_due_jobs() from public; grant execute on function public.expire_due_jobs() to authenticated;

-- First owner must be provisioned explicitly by the project owner/setup SQL; no automatic public claim function is exposed.

-- Secure push subscriptions: clients can create/update only through a narrow RPC; direct mutation is disabled.
drop policy if exists push_public_insert on public.push_subscriptions;
drop policy if exists push_public_update on public.push_subscriptions;
drop policy if exists push_public_delete on public.push_subscriptions;
drop policy if exists push_owner_read on public.push_subscriptions;
create policy push_owner_read on public.push_subscriptions for select to authenticated using (public.is_owner());
create or replace function public.upsert_push_subscription(p_endpoint text,p_p256dh text,p_auth text,p_user_agent text) returns void language plpgsql security definer set search_path=public as $$
begin
 if length(trim(p_endpoint))=0 or length(p_endpoint)>2000 or length(p_p256dh)>500 or length(p_auth)>500 then raise exception 'Invalid push subscription'; end if;
 if p_endpoint !~ '^https://[^[:space:]]+$' then raise exception 'Invalid push endpoint'; end if;
 insert into public.push_subscriptions(endpoint,p256dh,auth,user_agent,updated_at) values(p_endpoint,p_p256dh,p_auth,left(p_user_agent,500),now())
 on conflict(endpoint) do update set p256dh=excluded.p256dh,auth=excluded.auth,user_agent=excluded.user_agent,updated_at=now();
end; $$;
revoke all on function public.upsert_push_subscription(text,text,text,text) from public; grant execute on function public.upsert_push_subscription(text,text,text,text) to anon,authenticated;

-- Basic server-side analytics abuse guard: same visitor key/event type cannot create more than
-- one event within the short client cooldown window. This is defense-in-depth; it is not an
-- identity system and does not expose visitor data publicly.
create or replace function public.guard_analytics_event() returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.visitor_key is not null and exists(select 1 from public.analytics_events e where e.visitor_key=new.visitor_key and e.event_type=new.event_type and e.created_at > now()-interval '1 second') then
    raise exception 'Analytics rate limit exceeded';
  end if;
  return new;
end; $$;
drop trigger if exists analytics_rate_guard on public.analytics_events;
create trigger analytics_rate_guard before insert on public.analytics_events for each row execute function public.guard_analytics_event();
revoke all on function public.guard_analytics_event() from public;
